global using Xunit;
global using SimplexLab.Lwfix;
global using SimplexLab.Lwfix.Physics;
global using SimplexLab.Lwfix.Physics.Collision;
global using SimplexLab.Lwfix.Physics.Collision.Shapes;
global using SimplexLab.Lwfix.Physics.DataStructures;
global using SimplexLab.Lwfix.Physics.Dynamics;
global using SimplexLab.Lwfix.Physics.Dynamics.Constraints;
global using SimplexLab.Lwfix.Physics.LinearMath;
global using Real = SimplexLab.Lwfix.Fixed32;
global using MathR = SimplexLab.Lwfix.FMath;
