global using Xunit;
global using SimplexLab.Lwfix;
global using SimplexLab.LwfixPhysics.Jitter2;
global using SimplexLab.LwfixPhysics.Jitter2.Collision;
global using SimplexLab.LwfixPhysics.Jitter2.Collision.Shapes;
global using SimplexLab.LwfixPhysics.Jitter2.DataStructures;
global using SimplexLab.LwfixPhysics.Jitter2.Dynamics;
global using SimplexLab.LwfixPhysics.Jitter2.Dynamics.Constraints;
global using SimplexLab.LwfixPhysics.Jitter2.LinearMath;
global using Real = SimplexLab.Lwfix.Fixed32;
global using MathR = SimplexLab.Lwfix.FMath;
